"""guild settings

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-24 19:23:27.238529

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guild_settings",
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("max_repos", sa.Integer(), nullable=True),
        sa.Column("max_subscriptions", sa.Integer(), nullable=True),
        sa.Column("commits_allowed", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("blocked", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("blocked_reason", sa.Text(), nullable=True),
        sa.Column("blocked_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("manager_role_id", sa.BigInteger(), nullable=True),
        sa.Column("subscriber_role_id", sa.BigInteger(), nullable=True),
        sa.Column("default_channel_id", sa.BigInteger(), nullable=True),
        sa.Column("embed_style", sa.Text(), server_default="full", nullable=False),
        sa.Column(
            "show_asset_buttons", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("latest_access", sa.Text(), server_default="everyone", nullable=False),
        sa.Column(
            "latest_allow_public", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("guild_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("guild_settings")
    # ### end Alembic commands ###
